server:
  # 端口号
  port: ${DP_SERVER_PORT:8888}

# DataSource Config
spring:
  datasource:
    url: ${META_DB_URL:jdbc:postgresql://localhost:5432/develop}
    driver-class-name: org.postgresql.Driver
    username: develop
    password: develop

mybatis:
  # 配置mybatis xml文件路径
  mapper-locations: classpath:mapper/*.xml
  # 配置开启字段映射自动转驼峰
  configuration:
    map-underscore-to-camel-case: true

logging:
  # logback.xml配置文件的位置
  config: classpath:logback-spring.xml